#!/usr/bin/env bash
#
# Builds two dependency-free bundles from the files under src/:
#
#   preview.html   a complete HTML document — open it directly in a browser
#   artifact.html  the same page as a fragment (no <html>/<head>/<body>), which
#                  is the shape the Claude Artifact publisher expects
#
# Why this exists: the Vite app is the real deliverable, but running it needs
# Node. These bundles let anyone open the dashboard with nothing installed.
#
# There is one source of truth — src/. This script only strips ES module syntax
# and concatenates, so neither bundle can drift from the app it mirrors.
#
# Usage: ./scripts/build-standalone.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$PROJECT_ROOT/src"
PREVIEW_FILE="$PROJECT_ROOT/preview.html"
ARTIFACT_FILE="$PROJECT_ROOT/artifact.html"

# Concatenation order. Module-level `const` declarations are not hoisted, so
# data and theme constants must precede their consumers. Components are function
# declarations and so are order-independent; they are grouped by feature purely
# for readability.
SOURCE_FILES=(
  "data/mockData.js"
  "utils/chartTheme.js"
  "utils/formatters.js"
  "utils/portfolioMetrics.js"
  "utils/actionItemQueries.js"
  "components/ui/Card.jsx"
  "components/ui/Badge.jsx"
  "components/ui/InfoTooltip.jsx"
  "components/ui/SectionHeader.jsx"
  "components/ui/FilterSelect.jsx"
  "components/ui/TabNav.jsx"
  "components/ui/TabLink.jsx"
  "components/DashboardHeader.jsx"
  "components/PortfolioHeroMetric.jsx"
  "components/map/PortfolioMap.jsx"
  "components/actionItems/ActionItemFilters.jsx"
  "components/actionItems/ActionItemRow.jsx"
  "components/actionItems/ActionItemsPanel.jsx"
  "components/tracker/GatheringDataState.jsx"
  "components/tracker/ImplementationTimeline.jsx"
  "components/tracker/ImplementationControl.jsx"
  "components/tracker/PricingSuggestion.jsx"
  "components/tracker/BeforeAfterChart.jsx"
  "components/tracker/EffectivenessTracker.jsx"
  "components/benchmarking/CompetitiveGap.jsx"
  "components/benchmarking/BenchmarkingPanel.jsx"
  "App.jsx"
)

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

# Remove ES module syntax so every file can share one browser scope:
#   `import ... ;`     → dropped (handles multi-line imports, because an import
#                        statement never contains a semicolon before its end)
#   `export default X` → `X`
#   `export X`         → `X`
strip_module_syntax() {
  perl -0777 -pe "s/^import[^;]*;[ \t]*\r?\n//gm; s/^export default //gm; s/^export //gm" "$1"
}

# --- Shared fragments ------------------------------------------------------

# Design tokens, minus the Tailwind directive the CDN build does not need.
grep -v "@import 'tailwindcss';" "$SRC_DIR/index.css" > "$BUILD_DIR/styles.css"

{
  # Module imports are stripped at build time; the libraries arrive as globals
  # from the CDN tags and are destructured here instead.
  cat <<'PREAMBLE'
      const { useState } = React;
      const {
        CartesianGrid,
        LabelList,
        Line,
        LineChart,
        ReferenceLine,
        ResponsiveContainer,
        Tooltip,
        XAxis,
        YAxis,
      } = Recharts;

PREAMBLE

  for source_file in "${SOURCE_FILES[@]}"; do
    echo "      // ─── src/$source_file ───"
    strip_module_syntax "$SRC_DIR/$source_file"
    echo
  done

  echo "      ReactDOM.createRoot(document.getElementById('root')).render(<App />);"
} > "$BUILD_DIR/app.jsx"

# Third-party tags. Every host here is on the Artifact content-security policy's
# allowlist, so the same markup works locally and when published.
cat > "$BUILD_DIR/deps.html" <<'DEPS'
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Instrument+Sans:wght@400;500;600;700&display=swap"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.8.1/prop-types.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/recharts/2.12.7/Recharts.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.26.2/babel.min.js"></script>
DEPS

# --- preview.html: a complete, openable document ---------------------------

{
  cat <<'HEAD'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ReviewLoop — Review Intelligence for Property Managers</title>

    <!-- Generated by scripts/build-standalone.sh — edit files in src/, not this file. -->
HEAD
  cat "$BUILD_DIR/deps.html"
  echo "    <style>"
  cat "$BUILD_DIR/styles.css"
  cat <<'MID'
    </style>
  </head>
  <body>
    <div id="root"></div>

    <script type="text/babel">
MID
  cat "$BUILD_DIR/app.jsx"
  cat <<'TAIL'
    </script>
  </body>
</html>
TAIL
} > "$PREVIEW_FILE"

# --- artifact.html: the same page, without the document wrapper ------------

{
  echo "<title>ReviewLoop</title>"
  echo
  echo "<!-- Generated by scripts/build-standalone.sh — edit files in src/, not this file. -->"
  cat "$BUILD_DIR/deps.html"
  echo "<style>"
  cat "$BUILD_DIR/styles.css"
  cat <<'MID'
</style>

<div id="root"></div>

<script type="text/babel">
MID
  cat "$BUILD_DIR/app.jsx"
  echo "</script>"
} > "$ARTIFACT_FILE"

echo "Built:"
echo "  $PREVIEW_FILE   (open this in a browser)"
echo "  $ARTIFACT_FILE  (for publishing as a Claude Artifact)"
